### ISSUE TITLE
StardewHack Patches for 1.6

### ISSUE THREAD

**Issue by oversizedhoody** [bcmpinc/StardewHack#100]
So the updated Mods work. for the most part; SMAPI gives a "patch failed to apply cleanly" message however
[Here's the log for them; I'm using both Movement Speed and Tilled Soil Decay](https://smapi.io/log/d6467948a4b94e01b3ae0b1c2fe6ce90)

**Comment by JULIALIU0525** [comment]
Using the stardewhack v7.0.0 and got an error:

[StardewHack] Loaded StardewHack library v7.0.0 using Harmony v2.2.2.0.
[Movement Speed] Applying bytecode patches for bcmpinc.MovementSpeed.
[Movement Speed] The patch failed to apply cleanly. Usually this means the mod needs to be updated.
[Movement Speed] As a result, this mod does not function properly or at all.
[Movement Speed] Please upload your log file at https://log.smapi.io/ and report this bug at https://github.com/bcmpinc/StardewHack.
[Movement Speed] StardewHack.InstructionNotFoundException: Could not find instruction sequence (failed to match line 1: "ldc.i4.1 NULL"):
  call static StardewValley.Farmer StardewValley.Game1::get_player()
  ldc.r4 600
  ldloc.s
  mul
  conv.i4
  stfld Netcode.NetInt StardewValley.Farmer::toolHold
   at StardewHack.InstructionRange..ctor(List`1 insts, InstructionMatcher[] contains, Int32 start, Int32 step) in C:\Users\bauke\source\repos\StardewHack\StardewHack\InstructionRange.cs:line 70
   at StardewHack.MovementSpeed.ModEntry.Game1_UpdateControlInput_Chain() in C:\Users\bauke\source\repos\StardewHack\MovementSpeed\ModEntry.cs:line 70

**Comment by bcmpinc** [comment]
The script I used to gather the zip files for uploading, had net5.0 hard coded in it, so I ended uploading the last build against net5.0, which are actually build for SDV 1.5.6. TRhe new v7.1 upload is the actual new version.

**Comment by oversizedhoody** [comment]
thanks for the reply and the work you do!!!
