### ISSUE TITLE
[Wear more rings] should give an error when connecting with someone who does not have the mod installed.

### ISSUE THREAD

**Issue by Maxworld4** [bcmpinc/StardewHack#15]
Stardew hack can't run in multiplayers, why ? Can you fix that ?
my partner load eternely, and my terminal crash ...

**Comment by Maxworld4** [comment]
I load this mod with wearmorerings

**Comment by bcmpinc** [comment]
Do both of you have the mod installed? If not, that's what causes the crashes. The mod does not yet check this properly. If you do both have that mod installed, can you upload your log file and that of your partner to https://log.smapi.io/ ?

**Comment by Maxworld4** [comment]
yes we both have mods install.

**Comment by Maxworld4** [comment]
help ?

**Comment by bcmpinc** [comment]
You both need to have the WearMoreRings mod installed otherwise you indeed get an error during connection. I still need to implement something to refuse connection if someone has the mod installed but not others.
