### ISSUE TITLE
[Can you create ?] Better Transmutation

### ISSUE THREAD

**Issue by Maxworld4** [bcmpinc/StardewHack#16]
Can you create one mod like this ? 
https://www.nexusmods.com/stardewvalley/mods/2120?tab=description
because you are good and I like this mod, I don't wanna lose this mod :,(

**Comment by doi3kimngoc** [comment]
No
Because replace in Crafting Recipes Expanded

**Comment by bcmpinc** [comment]
See here: https://www.nexusmods.com/stardewvalley/mods/3142
