### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by PieWitch** [bcmpinc/StardewHack#21]
https://log.smapi.io/V2JTUf1B

After installing some mods yesterday, I cannot get through one day today without crashing.

**Comment by bcmpinc** [comment]
A memory corruption bug. It can be anything that's causing it. Including defective hardware. Similar crashes have been reported at:
https://steamcommunity.com/app/413150/discussions/1/2561864094350218207/
https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375/page-97#post-3219169
Though I doubt whether any of those can help you track down the issue or fix it.

**Comment by bcmpinc** [comment]
This crash happens during handling of sound playback and does not seem related to my mods.
