### ISSUE TITLE
[Craft Counter] Doesn't count how many times I've cooked dishes

### ISSUE THREAD

**Issue by void-arg** [bcmpinc/StardewHack#22]
I recently installed Craft Counter and it seems to be working fine for crafted items. However, it doesn't count how many times I've cooked dishes. The counter just says "Times cooked: 0" for every dish, even after I make a dish.

Specs: SMAPI 2.10.2 with Stardew Valley 1.3.33 on MacOS Unix 18.2.0.0

**Comment by bcmpinc** [comment]
That's odd. On my Linux PC it's working fine. I don't have MacOS so I can't test there. You're not running an older version of the mod? I.e. something prior to the current version 1.0. (This used to be broken in an earlier version.)

**Comment by FaVour-Wanderer** [comment]
It's like it has a conflict with ["Cooking Skill"](https://www.nexusmods.com/stardewvalley/mods/522?tab=description) mod.

**Comment by bcmpinc** [comment]
I see, that mod replaces the consumeIngredients method. (See https://github.com/spacechase0/CookingSkill/blob/8c00a07b68386f1a521d00ae1b355a82d5d26c9b/NewCraftingPage.cs) I patch that method to keep track of how often a recipe has been cooked. I'm not going to add compatibility for that.
