### ISSUE TITLE
[Craft Counter] Stopped working

### ISSUE THREAD

**Issue by minervamaga** [bcmpinc/StardewHack#23]
I suspect I may have a mod conflict, but Craft Counter suddenly stopped working for me.  The space where the counter should show is there, but blank.  See attached screenshot for reference.  Here is my SMAPI log as well: https://log.smapi.io/qXCY3Apz  This mod was previously working with JA/CFR, fyi.
![craft-counter-error](https://user-images.githubusercontent.com/37347445/53925422-89c7bb00-4045-11e9-9105-ae6ea132e8e9.png)

**Comment by bcmpinc** [comment]
The Remote Fridge Storage overrides the method that draws the text. See:
https://github.com/SoapStuff/Remote-Fridge-Storage/blob/0f201240455dfd927068505f334c65f96702e6f5/RemoteFridgeStorage/HarmonyRecipePatch.cs. So please report this as a bug there.
