### ISSUE TITLE
Movement Speed troubles with Mouse Move Mode

### ISSUE THREAD

**Issue by igoutta** [bcmpinc/StardewHack#3]
This mod have an issue patching the game with the mod of ylsama, Mouse Move Mode, from here: https://www.nexusmods.com/stardewvalley/mods/2614
I already told the other mod author so, I'm tellling you right know. 
[This is a link to an image about the trouble. ](https://imgur.com/a/VQRxLk8)

Thanks for your time.

**Comment by bcmpinc** [comment]
Hi. I can confirm that this is a bug in my mod. Thanks for reporting.

The problem is that both mods patch the method `StardewValley.Game1::UpdateControlInput`. This causes my patch method to be called twice, which it currently isn't programmed to deal with.
