### ISSUE TITLE
Wear more rings error

### ISSUE THREAD

**Issue by DuskTake** [bcmpinc/StardewHack#31]
the error says it wont be working because of stardewhack here is the log https://log.smapi.io/d7dc184acdc44e09838a2faec7584b5e

**Comment by noski** [comment]
Second on this. Here's my log: https://log.smapi.io/srKq1RT6

**Comment by kinsem** [comment]
I am getting the exact same error as well as seen in my log:
[(https://log.smapi.io/6d0e857004254b4d9235555ff2f78d6c)](url)

**Comment by BrandonPotter0** [comment]
https://log.smapi.io/52a082660cb042e4a21fadb6537ed9e9 Getting the same issue as well.

**Comment by bcmpinc** [comment]
The error on MacOS I've fixed, I'm still working on the error on Windows.
