### ISSUE TITLE
Error after 1.4.4 update to Stardew

### ISSUE THREAD

**Issue by SpringsSong** [bcmpinc/StardewHack#36]
https://smapi.io/log/3953708d7f3c4e75b1f20db0f1c1d56c

I received this error after Stardew updated to 1.4.4 this morning. The message said to report it here, so here I am with my log.

**Comment by trashxking** [comment]
Same here:

https://smapi.io/log/4bc32cb7c0ce42c9965bcae82b180b00

**Comment by MilarvozM** [comment]
https://smapi.io/log/875d23cfe74745cab07a5b1af134f942
same issue

**Comment by Gonzoen** [comment]
Getting the same issue with WearMoreRings
https://smapi.io/log/f15de37093c0411490dedace1a13dfe3

**Comment by bcmpinc** [comment]
Thanks for notifying me. I've fixed this and will upload a new release soon.
