### ISSUE TITLE
I got this error with the newest version. I'm playing in Stardew Valley v1.4.3

### ISSUE THREAD

**Issue by Deralik** [bcmpinc/StardewHack#37]
[Wear More Rings] Could not find instruction sequence (failed to match line 3: "brfalse Label56"):
  ldarg.s 10
  ldfld Netcode.NetRef`1[StardewValley.Objects.Ring] rightRing
  callvirt
  ldloc.2
  ldfld
  ldarg.0
  ldarg.s 10
  callvirt Void onMonsterSlay(StardewValley.Monsters.Monster, StardewValley.GameLocation, StardewValley.Farmer)
   at StardewHack.InstructionRange..ctor(List`1 insts, InstructionMatcher[] contains, Int32 start, Int32 step)
   at StardewHack.WearMoreRings.ModEntry.GameLocation_damageMonster()

**Comment by bcmpinc** [comment]
Either update Stardew Valley to 1.4.4 or install version 2.4 of the mods.
