### ISSUE TITLE
[Wear more rings] Doesn't work on Android.

### ISSUE THREAD

**Issue by Torwent** [bcmpinc/StardewHack#43]
https://smapi.io/log/69f4bb8aec01411db0682b4a4df3b11d

**Comment by bcmpinc** [comment]
This is a known issue. I'm waiting for 1.4.4 to be released on android before I'm going to add support.

**Comment by rholson** [comment]
https://smapi.io/log/66477c4d99b24b7a9e5d6c1c38d25532
Still broken and Android is now updated.

**Comment by SoulInfernoDE** [comment]
I can confirm it still doesn't work yet but I added the log.

Smapi 3.7.3

Lookup here:

https://smapi.io/log/3055f704ffa64680a23fda7276d1fd02

**Comment by Peekrasue2499** [comment]
I can't stand it 
we want mod wear more ring on Android

**Comment by bcmpinc** [comment]
I cannot support android, as I cannot do development on android.
