### ISSUE TITLE
[Movement Speed Mod] Move Mouse Mod Incompatible

### ISSUE THREAD

**Issue by MariahDawn** [bcmpinc/StardewHack#44]
Only reason I am posting this is because I see in an upgrade you had made this mod work with that one. I just loaded up the game after installing the mod and if I use the WASD keys it works great. With the mouse though I move normal speed. Isn't a big deal but I like using the mouse better. Thanks for the mod regardless, normal speed is just too slow sometimes.

**Comment by bcmpinc** [comment]
There's little I can do from my side of things. Your best bet is to ask the mod developer to update the code to solely use the result of `Game1.player.getMovementSpeed()` to determine the movement speed. In some cases it does, which means the speed increase should be applied, but in other cases it uses `Game1.player.speed` so the speed increase is not applied.

See https://github.com/ylsama/RightClickMoveMode/blob/master/RightClickMoveMode/ModEntry.cs#L937.
