### ISSUE TITLE
Not working on Windows with Steam

### ISSUE THREAD

**Issue by KFisch2014** [bcmpinc/StardewHack#46]
Hello.  I recently downloaded the stardewhack onto my pc. I play stardew through steam. In my SMAPI log it states the mods that require stardewhack need the stardewhack even though it is install. Please advise.

**Comment by bcmpinc** [comment]
Please upload your log file to https://smapi.io/log/ and post a link here.

**Comment by KFisch2014** [comment]
https://smapi.io/log/c940d297501c4a8782800a2e3a25ed67

I know it says there are a bunch of other mods it is skipping, but I have completely uninstalled and deleted the files for all mods except for StardewHack and WearMoreRings. I even uninstall SMAPI, uninstall ALL mods, rebooted my computer, then installed SMAPI, StardewHack and WearMoreRings. For some reason it still thinks those mods are there.

**Comment by bcmpinc** [comment]
Do you have this mod installed: https://www.nexusmods.com/stardewvalley/mods/3213? Because the log indicates you don't.

**Comment by KFisch2014** [comment]
Yes, I have the Stardew Hack installed

**Comment by KFisch2014** [comment]
![Picture1](https://user-images.githubusercontent.com/67445175/85873907-cfab1400-b79f-11ea-83ae-46ae8d39623f.png)

**Comment by bcmpinc** [comment]
Can you show a screenshot of this folder: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods
It should contain a folder named StardewHack, but I suspect it doesn't.

**Comment by KFisch2014** [comment]
![Picture1](https://user-images.githubusercontent.com/67445175/85888226-2839db80-b7b7-11ea-9edb-ee3c71851889.png)

It is there. This is the issue I had posted about, it states it is not installed, but it is.

**Comment by bcmpinc** [comment]
It seems this is an issue with Vortex and SMAPI. I've heard before mentioned that it often doesn't work properly. Instead of using vortex, you might want to install the mods manually. Or ask for help on [discrod](https://smapi.io/community) or [reddit](https://reddit.com/r/SMAPI).

I've no experience with vortex, so I cannot help you further.
