### ISSUE TITLE
[WearMoreRings] ChestsAnywhere conflict?

### ISSUE THREAD

**Issue by ayourk** [bcmpinc/StardewHack#52]
There seems to be a conflict between Chest Anywhere and WearMoreRings.  Any time I add all my rings to my character then open ChestAnywhere, I appear to open a chest containing the rings I just equipped that exists on my farm, but I haven't placed a chest on my farm.  My chests only exist within my farm house.

**Comment by bcmpinc** [comment]
My mod places a chest on your farm and uses that to store the rings you have equipped inside of it.

**Comment by ayourk** [comment]
By hiding the chest, you've effectively fixed this issue.  I'm a bit surprised you didn't add these rings to some sort of config.json in the mod folder.

**Comment by bcmpinc** [comment]
I used to do that, but with the combined rings for example, that would no longer work, as the ring contains metadata which I didn't store. This solution solves that issue, as well as works properly with modded rings and furthermore solves the issue of network synchronization.
