### ISSUE TITLE
[AlwaysScrollMap] Separate key bindings for indoor and outdoor toggling

### ISSUE THREAD

**Issue by nathan-alden-sr** [bcmpinc/StardewHack#56]
I've found permanent map scrolling to be useful only outdoors when planting massive farms. Indoors, the default behavior seems fine. Unfortunately, the key binding affects both options. It would be nice to have separate key bindings for each so I can only toggle outdoor scrolling.

**Comment by bcmpinc** [comment]
I don't understand you question. If you're indoors, the toggle button toggles indoor scrolling. If you're outdoors, the toggle button toggles outdoor scrolling. Do you want separate keys, so you can switch outdoor scrolling while you are indoors? Why would that be useful?

**Comment by nathan-alden-sr** [comment]
Oh, I wasn't aware it worked that way! Thanks; the current behavior is fine.
