### ISSUE TITLE
[Wear More Rings] and [Bigger Backpack] Failing at startup

### ISSUE THREAD

**Issue by Ellysssa** [bcmpinc/StardewHack#61]
[Wear More Rings] and [Bigger Backpack] No longer work after SMAPI update 3.12.0

https://smapi.io/log/c9e1511cb871412c8a27252d60aa94c1

**Comment by WagnerGFX** [comment]
It seems to also affect [Harvest With Scythe]

https://smapi.io/log/57f8269fe1f4442bbf635c1024541ff3

**Comment by bcmpinc** [comment]
With the exception of Wear More Rings and Tilled Soil Decay, this issue is fixed in version 5.0.

**Comment by bcmpinc** [comment]
Wear More Rings and Tilled Soil Decay will be tracked in #64.
