### ISSUE TITLE
[WearMoreRings] and [TilledSoilDecay] don't work in SMAPI 3.12.0

### ISSUE THREAD

**Issue by highmax1** [bcmpinc/StardewHack#64]
Log:https://smapi.io/log/b227f18ca8654f4c8ddfd82685c187d4

**Comment by highmax1** [comment]
Oh and Also I Already updated [WearMorerings] It still Say Need to Update it.

**Comment by littleninja78** [comment]
I had the same issue also updated WearMorerings and still saying the issue may be due to needing an update.
https://smapi.io/log/2f8fa89a0a024a90a8cf3bad51e01298

**Comment by PupOgre** [comment]
Same issue here. https://smapi.io/log/1400b0e93c53445aaef667bd1437dd3c

**Comment by bcmpinc** [comment]
I haven't been able to update Wear More Rings for the new version of SMAPI. I have no idea where the "Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true." error comes from, what it means or why it happens.

**Comment by FlexxicE** [comment]
The late bound problem seems to be triggered by bigger backpack, if it's disabled the problem gets reduced to the one-line error in "littleninja"s log, where only the method isn't found that more rings is looking for

> 
> 
> I haven't been able to update Wear More Rings for the new version of SMAPI. I have no idea where the "Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true." error comes from, what it means or why it happens.
