### ISSUE TITLE
[HarvestWithScythe] some issue happening before and after updating everything

### ISSUE THREAD

**Issue by Charliecat16** [bcmpinc/StardewHack#65]
https://smapi.io/log/e709a1091f364d73ab957375c2d2c5bc here is the log, I have no clue what is happening and even how to actually report this. I tried to follow the instructions but idk what i'm doing

**Comment by bcmpinc** [comment]
You need to update Stardew Hack, Harvest With Scythe and Fix Animal Tools to version 5.0.
