### ISSUE TITLE
Problem with Stardewhack

### ISSUE THREAD

**Issue by JokerBTA** [bcmpinc/StardewHack#70]
I recent updated SMAPI and Stardew Valley to the new beta and I ran into some issues with Stardewhack and Harvest with Scythe Mods

Here is my log: https://smapi.io/log/d2f990607ab743c5914b692ca29159e8

**Comment by suburbanmisfits** [comment]
Also getting a Similar Error

https://smapi.io/log/33b6964cfd934ec9b7861ccb419ad31f

**Comment by bcmpinc** [comment]
I've uploaded a beta version of harvest with scythe for SDV-1.5.5-beta: https://www.nexusmods.com/stardewvalley/mods/2731?tab=files

**Comment by JokerBTA** [comment]
Downloaded the beta and it works fine! You can close the issue if you like!
