### ISSUE TITLE
[WearMoreRings] In multiplayer, extra rings disappear after the day ends for player 2

### ISSUE THREAD

**Issue by briankendall** [bcmpinc/StardewHack#72]
Just tried out this mod in a two player map played split-screen. The rings on the second player disappeared from existence at the start of the next day, though the rings on player 1 remained equipped.

**Comment by bcmpinc** [comment]
Thanks for reporting.

**Comment by bcmpinc** [comment]
Starting from version 6.3 this issue should be fixed.
