### ISSUE TITLE
Harvest With Scythe Failing to Patch

### ISSUE THREAD

**Issue by unlitday** [bcmpinc/StardewHack#73]
Hello! Here's my SMAPI log: https://smapi.io/log/0e7eed71845a49e697cc07ddd2b7358a
I'll be very honest, I have no idea how to code and I'm not technologically inclined, so it's a miracle I'm even capable of running Stardew mods at all. I actually made this account specifically to report the bug since SMAPI requested I do. I don't understand what the issue is with Harmony and Stardew Hack failing to apply the bytecode patches from Harvest With Scythe. Hope my log helps resolve a potential problem following the 1.5.5 update! Sorry if it's just me.

**Comment by bcmpinc** [comment]
You need to install version 5.3-beta.0 of the mod.

**Comment by bcmpinc** [comment]
I uploaded a new build with version number 5.5.
