### ISSUE TITLE
[WearMoreRings,BiggerBackpacks,AlwaysScrollMap] Patch failed to apply cleanly for 1.5.5

### ISSUE THREAD

**Issue by justastranger** [bcmpinc/StardewHack#75]
[Log can be found here](https://smapi.io/log/4b8cdd0509dc4bf8979bd10a3c415d99)

There are 6 of your mods in the log, 3 of which I've found beta updates for so far.

**Comment by rodrigovda** [comment]
This happened to me too, in my case the StardewHack mod I'm trying to use is Harvest With Scythe.

[Log can be found here](https://smapi.io/log/4b8cdd0509dc4bf8979bd10a3c415d99)

**Comment by justastranger** [comment]
> This happened to me too, in my case the StardewHack mod I'm trying to use is Harvest With Scythe.
> 
> [Log can be found here](https://smapi.io/log/4b8cdd0509dc4bf8979bd10a3c415d99)

You appear to have used the link to my log instead of yours.

**Comment by justastranger** [comment]
Here's a new [log](https://smapi.io/log/ab071b7a3e204358b6170b982420c51f) using the released betas for Harvest With Scythe, Tilled Soil Decay, and Grass Growth. Harvest With Scythe and Grass Growth still fail to apply patches.

**Comment by rodrigovda** [comment]
Ok I found the issue, with 1.5.5 you have to install the BETA version of the mod (I was using only harvest with scythe, Idk if any other mod must be updated):
[Harvest With Scythe-2731-5-3-beta-0-1631128844.zip](https://www.nexusmods.com/stardewvalley/mods/2731?tab=files&file_id=45017)

**Comment by bcmpinc** [comment]
I uploaded a new build with version number 5.5. These are effectively the same as the beta versions, but don't have a beta version number.

**Comment by justastranger** [comment]
Even with these new builds I'm counting 20 `StardewHack.InstructionNotFoundException`s across 5 StardewHack mods (half being from Wear More Rings).

![StardewModdingAPI_2021-12-05_09-20-17](https://user-images.githubusercontent.com/6827479/144752633-243658b8-38ed-4ed7-967a-cfae6318d2d5.png)

[Log here](https://smapi.io/log/ccdee50d273e4dbd84d42c33fed3125c)

**Comment by bcmpinc** [comment]
@justastranger : please try again with the other failing mods removed. I cannot reproduce the errors and I want to be certain that your issues are not caused by any of the other failing mods.

**Comment by justastranger** [comment]
Updating to the latest hot patch for 1.5.5 and release of SMAPI caused the errors to disappear, though there are still 3 failed patches for WearMoreRings logged as trace. [Log here.](https://smapi.io/log/a6156f55464d4b5ebfe323473b0230a9) I'm a little boggled by this since they came out after your updates to 1.5.5 and just removing the other erroring mods didn't change anything.

**Comment by justastranger** [comment]
> @justastranger I assume you're on GOG? There was an issue with the GOG / Game Pass build which changed how some method instructions would be compiled, which in turn would break mods which depend on transpilers.

 - Pathoschild on Discord

**Comment by bcmpinc** [comment]
The Trace logs are intentional. Some patches have multiple versions and it just tries them until one works, but if none of them work I still need all the error messages to see what goes wrong. So they're printed as trace.
