### ISSUE TITLE
[HarvestWithScythe] Add support for harvest only with golden scythe

### ISSUE THREAD

**Issue by rodrigovda** [bcmpinc/StardewHack#76]
I have always liked this mod because of what it adds specially in the late game, however I find it a little too OP.

I likled the idea of a poorly made mod called "Harvest with golden scythe" This mod never worked as intended.

The idea is to have a "Harvest with scythe mod" but for it to only work with the **golden** scythe.

That way there's player progression and the golden scythe has a specific purpose other than aesthetics, so there is an actual good reason to aim for getting it.

I know nothing about how this mod works, but since at some point it did not work with golden scythe, my guess is that it can handle each scythe differently, so could there be a config switch so the mod only enables harvesting with scythe for the golden scythe?

I personally thing this would totally balance this mod being too "cheaty" for some follks.

EDIT: Typo in Title and clarification on why using the referenced mod is not an actual option.

**Comment by rodrigovda** [comment]
Alright, I found out that the mod already supports this feature by editing the "config.json" file.

For each option "Flowers", "Forage", "SpringOnion":, "PluckableCrops", "ScythableCrops" you can use one of these values:

**- HAND**: Only harvest by hand
**- GOLD**: Harvest by hand or by using the golden scythe (but not the normal scythe)
**- SCYTHE**: Harvest only by schythe (any scythe).
**- BOTH**: Harvest in any way: by hand or by any scythe.

This should be mentioned in the main page of the mod, either on nexusmods or github, or both.

**Comment by bcmpinc** [comment]
It actually is noted in the mod's readme and thus on both nexusmods and github, but I guess I could reformat it to make it more noticable.
