### ISSUE TITLE
HarvestWithScythe Update Required

### ISSUE THREAD

**Issue by Skym365** [bcmpinc/StardewHack#77]
HarvestWithScythe needs to be updated for the recent Stardew patch. Just to ensure the problem with the current version is brought to attention, I copied my recent log.

https://smapi.io/log/3ded8038d60041cda92e293fda24c554

There's nothing wrong with my game running, but I love this mod so I'd love to see it updated soon!

**Comment by bcmpinc** [comment]
For now you can install the beta version from the optional files.

**Comment by bcmpinc** [comment]
I uploaded a new build with version number 5.5.
