### ISSUE TITLE
Issue with [TilledSoilDecay]

### ISSUE THREAD

**Issue by ac72692** [bcmpinc/StardewHack#78]
[Tilled Soil Decay] Applying bytecode patches for bcmpinc.TilledSoilDecay.
[Tilled Soil Decay] The patch failed to apply cleanly. Usually this means the mod needs to be updated.
[Tilled Soil Decay] As a result, this mod does not function properly or at all.
[Tilled Soil Decay] Please upload your log file at https://log.smapi.io/ and report this bug at https://github.com/bcmpinc/StardewHack.
[Tilled Soil Decay] StardewHack.InstructionNotFoundException: Could not find instruction sequence (failed to match line 3: "ldarg.0 NULL"):
  isinst StardewValley.TerrainFeatures.HoeDirt
  callvirt StardewValley.Crop StardewValley.TerrainFeatures.HoeDirt::get_crop()
  brtrue
  ldsfld System.Random StardewValley.Game1::random
  callvirt
  ldc.r8
   at StardewHack.InstructionRange..ctor(List`1 insts, InstructionMatcher[] contains, Int32 start, Int32 step) in C:\Users\bauke\source\repos\StardewHack\StardewHack\InstructionRange.cs:line 70
   at StardewHack.TilledSoilDecay.ModEntry.Farm_DayUpdate() in C:\Users\bauke\source\repos\StardewHack\TilledSoilDecay\ModEntry.cs:line 74

**Comment by bcmpinc** [comment]
**Please upload your log file at https://log.smapi.io/**. Can you give me a link to the entire log file. Without the version information I cannot really help you.

**Comment by ac72692** [comment]
https://smapi.io/log/62ed550115ec4368976bcf964bc6eed2
It seems ot be a problem with Stardew 1.5.6 update (according to a thread
on Nexus Mods)

AC

**Comment by bcmpinc** [comment]
I've released a new version of Tilled Soil Decay (v5.6) that fixes this compatibility issue with SDV 1.5.6.
