### ISSUE TITLE
[TilledSoilDecay] Re-added Seasonal Decay feature not working?

### ISSUE THREAD

**Issue by Almech-Alfarion** [bcmpinc/StardewHack#79]
Not sure if I'm doing something wrong, or if the added config isn't working, but I've tested the update on both the Vanilla Standard and Grandpa's Farm from SVE, and the no decay over season change doesn't seem to be working? I've even set the "DryingRate" to 0.0 and a goodly chunk of my tilled soil is still disappearing even with being fully watered and full sprinkler coverage unless something has been planted in it already.

I'm not getting any errors in my SMAPI Log, but I'll put it here anyway just in case something's interfering that I don't know about.

[SMAPI.io Log](https://smapi.io/log/5b2d30f44f35467a96441160c4d87191)

**Comment by bcmpinc** [comment]
I was convinced that tilled soil decay during season change was removed, as I was unable to find it. I guess it isn't but instead is moved to some really well hidden place in the code.
