### ISSUE TITLE
Movement Speed mod not working 100%

### ISSUE THREAD

**Issue by DangerousWithRocks** [bcmpinc/StardewHack#80]
I downloaded this mod last night and it was working great for a while. I constantly have it at max speed. I booted up the game for the 3rd time today and it's not working right. 5x multiplier is basically 2x and default 1.5 speed changes the speed to a negative multiplier almost. I'm walking when I'm running. The speed icon is still at the top of the screen. I've deleted the mod and re-installed it a couple times now and no issues come up in SMAPI. Any ideas on what I can do?

**Comment by DangerousWithRocks** [comment]
Update after sleeping in game. It's working just fine now...so that's very odd. I'll keep this updated if it goes back to not working properly.

**Comment by DangerousWithRocks** [comment]
Update again. My game rebooted randomly, booting it back up causes the mod to act up again. Back to slower speeds.

**Comment by bcmpinc** [comment]
Must be an interaction with some other mod. I can't tell which one though.
