### ISSUE TITLE
Conflict with tractor mod

### ISSUE THREAD

**Issue by Luos83** [bcmpinc/StardewHack#81]
Hey hey, awesome mod, especially as a solo player on a big multiplayer farm!

I noticed a bug, however!
It seems the Tractor Mod interferes with the Movement Speed mod ( https://www.nexusmods.com/stardewvalley/mods/1401 ) resetting the movement speed back to vanilla after using the tractor.
The movement speed kicks back in after a good night of ingame sleep, however.
I'll also let the creator of the other mod know and post this on your github as well.

Take care, and have a great week!

Smapi log: https://smapi.io/log/3897702aea6f4eb9bfa811253be167d4

**Comment by bcmpinc** [comment]
I've given up trying to support the tractor mod. It doe s a lot of weird stuff and its impossible to detect that the player is on the tractor, so I've given up trying to support that mod. I'm sure Pathos thinks the same about my mod, so you have to chose which one to use.
