### ISSUE TITLE
[Wear More Rings] Chest went missing!

### ISSUE THREAD

**Issue by Wudonggg** [bcmpinc/StardewHack#84]
If continue the next day of the game, there will not happen this error. But start again Stardew Valley or return to the title screen, then load into the game and the error will happen. Then it will just leave 2 rings in the rings slot...
Here is the SMAPI log [https://smapi.io/log/866a54e4f2a54129845b0ea4688cba35](url)

**Comment by bcmpinc** [comment]
Since version 6.0 I store the rings differently so this can no longer happen.
