### ISSUE TITLE
出现error

### ISSUE THREAD

**Issue by 24k12315** [bcmpinc/StardewHack#86]
![image](https://user-images.githubusercontent.com/118600831/215301410-31a8ee6f-ab98-42ca-8c9c-7458de906b82.png)
这样影响模组运行吗，该如何处理

**Comment by bcmpinc** [comment]
It's just a warning. It pops up due to how I implemented the mods. You can safely ignore it. It's just there as a recommendations on what to try first when people do encounter problems.
