### ISSUE TITLE
Combination Rings

### ISSUE THREAD

**Issue by termiteQC** [bcmpinc/StardewHack#87]
I play in solo and my mod is correctly installed but i can't see my 6 new rings slots... I only see my 2 normal rings slots with one of them having a combination ring. What the hell is that? x)

**Comment by bcmpinc** [comment]
You're using a mod that's incompatible with wear more rings, due to it overriding the inventory screen. Without further information I can't tell what mod is causing this issue. Though, it might have listed it in the readme.

**Comment by termiteQC** [comment]
I found the problem mate! I was just dumb as fck... I have a laptop and a PC... I play SV on my laptop when i work so i grab my MODS folder from my PC to my laptop. One day later i add WearMoreRings on my PC and not on my Laptop... I am so dumb man sorry for taking your time xD
