### ISSUE TITLE
After the SMAPI mobile update, stardewhack is not applicable.

### ISSUE THREAD

**Issue by haeseull** [bcmpinc/StardewHack#88]
![KakaoTalk_20230405_095811531](https://user-images.githubusercontent.com/126547353/229954585-162ba846-710f-46da-bed2-b54bc5a013bf.jpg)

I downloaded the most up-to-date mode, but this pop-up comes out.

https://smapi.io/log/870eb49683544b13b1ff7ac1f38709d2

**Comment by bcmpinc** [comment]
Android is not supported as I'm not able to do development on android.
